apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager-prod
  namespace: argocd
spec:
  project: taskmanager
  source:
    repoURL: https://github.com/attila-somogyvari/task-manager-alkfejl.git
    targetRevision: main
    path: deployment/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: taskmanager-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
