apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: taskmanager
  namespace: argocd
spec:
  description: Task Manager alkalmazas GitOps telepitesi projekt
  sourceRepos:
    - https://github.com/attila-somogyvari/task-manager-alkfejl.git
  destinations:
    - namespace: taskmanager-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
